# Generated by Django 3.2.8 on 2021-10-16 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionapp', '0002_question_question_hit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-id']},
        ),
    ]
