# Generated by Django 3.2.8 on 2021-10-16 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionapp', '0003_alter_question_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='question/'),
        ),
    ]
