# Generated by Django 3.2.8 on 2021-10-16 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='top_fixed',
            field=models.BooleanField(default=True),
        ),
    ]
